---

#   Section 5.1 Configure cron

- name: 5.1.1 Ensure cron daemon is enabled (Scored)
  service: >
    name=crond
    enabled=yes
    state=started
  tags:
    - scored
    - section5.1
    - section5.1.1

- name: 5.1.2 Ensure permissions on /etc/crontab are configured (Scored)
  file: >
    path=/etc/crontab
    owner=root
    group=root
    mode=0600
  tags:
    - scored
    - section5.1
    - section5.1.2

- name: 5.1.3 Ensure permissions on /etc/cron.hourly are configured (Scored)
  file: >
    path=/etc/cron.hourly
    owner=root
    group=root
    mode=0600
  tags:
    - scored
    - section5.1
    - section5.1.3

- name: 5.1.4 Ensure permissions on /etc/cron.daily are configured (Scored)
  file: >
    path=/etc/cron.daily
    owner=root
    group=root
    mode=0600
  tags:
    - scored
    - section5.1
    - section5.1.4

- name: 5.1.5 Ensure permissions on /etc/cron.weekly are configured (Scored)
  file: >
    path=/etc/cron.weekly
    owner=root
    group=root
    mode=0600
  tags:
    - scored
    - section5.1
    - section5.1.5

- name: 5.1.6 Ensure permissions on /etc/cron.monthly are configured (Scored)
  file: >
    path=/etc/cron.monthly
    owner=root
    group=root
    mode=0600
  tags:
    - scored
    - section5.1
    - section5.1.6

- name: 5.1.7 Ensure permissions on /etc/cron.d are configured (Scored)
  file: >
    path=/etc/cron.d
    state=directory
    owner=root
    group=root
    mode=0600
  tags:
    - scored
    - section5.1
    - section5.1.7

- name: 5.1.8 Ensure at/cron is restricted to authorized users (Scored)
  file: >
    path=/etc/at.deny
    state=absent
  tags:
    - scored
    - section5.1
    - section5.1.8

- name: 5.1.8 Ensure at/cron is restricted to authorized users (Scored)
  file: >
    path=/etc/at.allow
    state=touch
    owner=root
    group=root
    mode=0600
  tags:
    - scored
    - section5.1
    - section5.1.8

- name: 5.1.8 Ensure at/cron is restricted to authorized users (Scored)
  file: >
    path=/etc/cron.deny
    state=absent
  tags:
    - scored
    - section5.1
    - section5.1.8

- name: 5.1.8 Ensure at/cron is restricted to authorized users (Scored)
  file: >
    path=/etc/cron.allow
    state=touch
    owner=root
    group=root
    mode=0600
  tags:
    - scored
    - section5.1
    - section5.1.8

#   Section 5.2 SSH Server Configuration

- name: 5.2.1 Ensure permissions on /etc/ssh/sshd_config are configured (Scored)
  file: >
    path=/etc/ssh/sshd_config
    owner=root
    group=root
    mode=0600
  notify: Reload sshd
  tags:
    - scored
    - section5.2
    - section5.2.1

- name: 5.2.2 Ensure SSH Protocol is set to 2 (Scored)
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp="^Protocol " line="Protocol 2"
  notify: Reload sshd
  tags:
    - scored
    - section5.2
    - section5.2.2

- name: 5.2.3 Ensure SSH LogLevel is set to INFO (Scored)
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp="^LogLevel "
    line="LogLevel INFO"
  notify: Reload sshd
  tags:
    - scored
    - section5.2
    - section5.2.3

- name: 5.2.4 Ensure SSH X11 forwarding is disabled (Scored)
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp="^X11Forwarding "
    line="X11Forwarding no"
  notify: Reload sshd
  tags:
    - scored
    - section5.2
    - section5.2.4

- name: 5.2.5 Ensure SSH MaxAuthTries is set to 4 or less (Scored)
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp="^MaxAuthTries "
    line="MaxAuthTries 4"
  notify: Reload sshd
  tags:
    - scored
    - section5.2
    - section5.2.5

- name: 5.2.6 Ensure SSH IgnoreRhosts is enabled (Scored)
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp="^IgnoreRhosts "
    line="IgnoreRhosts yes"
  notify: Reload sshd
  tags:
    - scored
    - section5.2
    - section5.2.6

- name: 5.2.7 Ensure SSH HostbasedAuthentication is disabled (Scored)
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp="^HostbasedAuthentication "
    line="HostbasedAuthentication no"
  notify: Reload sshd
  tags:
    - scored
    - section5.2
    - section5.2.7

- name: 5.2.8 Ensure SSH root login is disabled (Scored)
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp="^PermitRootLogin "
    line="PermitRootLogin no"
  notify: Reload sshd
  tags:
    - scored
    - section5.2
    - section5.2.8

- name: 5.2.9 Ensure SSH PermitEmptyPasswords is disabled (Scored)
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp="^PermitEmptyPasswords "
    line="PermitEmptyPasswords no"
  notify: Reload sshd
  tags:
    - scored
    - section5.2
    - section5.2.9

- name: 5.2.10 Ensure SSH PermitUserEnvironment is disabled (Scored)
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp="^PermitUserEnvironment "
    line="PermitUserEnvironment no"
  notify: Reload sshd
  tags:
    - scored
    - section5.2
    - section5.2.10

- name: 5.2.11 Ensure only approved ciphers are used (Scored)
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp="^Ciphers "
    line="Ciphers aes128-ctr,aes192-ctr,aes256-ctr"
  notify: Reload sshd
  tags:
    - scored
    - section5.2
    - section5.2.11

- name: 5.2.12 Ensure only approved MAC algorithms are used (Scored)
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp="^MACs "
    line="MACs hmac-sha2-512,hmac-sha2-256"
  notify: Reload sshd
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6") or
        (ansible_distribution == "RedHat" and ansible_distribution_major_version == "6")
  tags:
    - scored
    - section5.2
    - section5.2.12

- name: 5.2.12 Ensure only approved MAC algorithms are used (Scored)
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp="^MACs "
    line="MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com"
  notify: Reload sshd
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7") or
        (ansible_distribution == "RedHat" and ansible_distribution_major_version == "7")
  tags:
    - scored
    - section5.2
    - section5.2.12

- name: 5.2.13 Ensure SSH Idle Timeout Interval is configured (Scored)
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp="^ClientAliveInterval "
    line="ClientAliveInterval 300"
  notify: Reload sshd
  tags:
    - scored
    - section5.2
    - section5.2.13

- name: 5.2.13 Ensure SSH Idle Timeout Interval is configured (Scored)
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp="^ClientAliveCountMax "
    line="ClientAliveCountMax 0"
  notify: Reload sshd
  tags:
    - scored
    - section5.2
    - section5.2.13

- name: 5.2.14 Ensure SSH LoginGraceTime is set to one minute or less (Scored)
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp="^LoginGraceTime "
    line="LoginGraceTime 60"
  notify: Reload sshd
  tags:
    - scored
    - section5.2
    - section5.2.14

- name: 5.2.15 Ensure SSH access is limited (Scored)
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp="^AllowGroups "
    line="AllowGroups {{ ssh_allow_groups }}"
  when: ssh_allow_groups is defined
  notify: Reload sshd
  tags:
    - scored
    - section5.2
    - section5.2.15

- name: 5.2.15 Ensure SSH access is limited (Scored)
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp="^AllowUsers "
    line="AllowUsers {{ ssh_allow_users }}"
  when: ssh_allow_users is defined
  notify: Reload sshd
  tags:
    - scored
    - section5.2
    - section5.2.15

- name: 5.2.15 Ensure SSH access is limited (Scored)
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp="^DenyGroups "
    line="DenyGroups {{ ssh_deny_groups }}"
  when: ssh_deny_groups is defined
  notify: Reload sshd
  tags:
    - scored
    - section5.2
    - section5.2.15

- name: 5.2.15 Ensure SSH access is limited (Scored)
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp="^DenyUsers "
    line="DenyUsers {{ ssh_deny_users }}"
  when: ssh_deny_users is defined
  notify: Reload sshd
  tags:
    - scored
    - section5.2
    - section5.2.15

- name: 5.2.16 Ensure SSH warning banner is configured (Scored)
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp="^Banner "
    line="Banner /etc/issue.net"
  notify: Reload sshd
  tags:
    - scored
    - section5.2
    - section5.2.16

#   Section 5.3 Configure PAM

- name: 5.3.1 - 5.3.4 Configure PAM (Scored)
  template:
    src: etc/pam.d/rhel-6/system-auth-ac.j2
    dest: /etc/pam.d/system-auth-ac
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_major_version == "6"
  tags:
    - scored
    - section5.3
    - section5.3.1
    - section5.3.2
    - section5.3.3
    - section5.3.4

- name: 5.3.1 - 5.3.4 Configure PAM (Scored)
  template:
    src: etc/pam.d/rhel-6/password-auth-ac.j2
    dest: /etc/pam.d/password-auth-ac
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_major_version == "6"
  tags:
    - scored
    - section5.3
    - section5.3.1
    - section5.3.2
    - section5.3.3
    - section5.3.4

- name: Gather pwquality configuration
  command: "cat /etc/security/pwquality.conf"
  register: pwquality_config
  changed_when: no
  when: ansible_distribution_major_version == "7"
  tags:
    - scored
    - section5.3
    - section5.3.1

- name: 5.3.1 Ensure password creation requirements are configured (Scored)
  command: "authconfig --update --{{ item }}"
  when:
    - ansible_distribution_major_version == "7"
    - ( "minlen = %s" % pam.password_quality.passminlen not in pwquality_config.stdout ) or
      ( "dcredit = %s" % pam.password_quality.reqdigit|ternary('-1', '0') not in pwquality_config.stdout ) or
      ( "ucredit = %s" % pam.password_quality.requpper|ternary('-1', '0') not in pwquality_config.stdout ) or
      ( "lcredit = %s" % pam.password_quality.reqlower|ternary('-1', '0') not in pwquality_config.stdout ) or
      ( "ocredit = %s" % pam.password_quality.reqother|ternary('-1', '0') not in pwquality_config.stdout ) or
      ( "minclass = %s" % pam.password_quality.passminclass not in pwquality_config.stdout ) or
      ( "maxrepeat = %s" % pam.password_quality.passmaxrepeat not in pwquality_config.stdout ) or
      ( "maxclassrepeat = %s" % pam.password_quality.passmaxclassrepeat not in pwquality_config.stdout )
  with_items:
    - "passminlen={{ pam.password_quality.passminlen }}"
    - "{{ pam.password_quality.reqdigit | ternary('enablereqdigit', 'disablereqdigit') }}"
    - "{{ pam.password_quality.requpper | ternary('enablerequpper', 'disablerequpper') }}"
    - "{{ pam.password_quality.reqlower | ternary('enablereqlower', 'disablereqlower') }}"
    - "{{ pam.password_quality.reqother | ternary('enablereqother', 'disablereqother') }}"
    - "passminclass={{ pam.password_quality.passminclass }}"
    - "passmaxrepeat={{ pam.password_quality.passmaxrepeat }}"
    - "passmaxclassrepeat={{ pam.password_quality.passmaxclassrepeat }}"
  tags:
    - scored
    - section5.3
    - section5.3.1

- name: Gather password-auth configuration
  command: "cat /etc/pam.d/password-auth"
  register: passwordauth_config
  changed_when: no
  when: ansible_distribution_major_version == "7"
  tags:
    - scored
    - section5.3
    - section5.3.2

- name: 5.3.2 Ensure lockout for failed password attempts is configured (Scored)
  command: authconfig --enablefaillock --faillockargs="deny={{ pam.faillock.deny }} unlock_time={{ pam.faillock.unlock_time }}" --update
  when:
    - ansible_distribution_major_version == "7"
    - pam.faillock.enabled
    - ( "deny=%s" % pam.faillock.deny not in passwordauth_config.stdout ) or
      ( "unlock_time=%s" % pam.faillock.unlock_time not in passwordauth_config.stdout )
  tags:
    - scored
    - section5.3
    - section5.3.2

- name: 5.3.3 Ensure password reuse is limited (Scored)
  debug: msg="*** Manually update password-auth and system-auth."
  tags:
    - scored
    - section5.3
    - section5.3.3

#   Section 5.4 User Accounts and Environment

- name: 5.4.1.1 Ensure password expiration is 90 days or less (Scored)
  lineinfile: >
    backup=yes
    state=present
    dest=/etc/login.defs
    backrefs=yes
    regexp="^PASS_MAX_DAYS\s+"
    line="PASS_MAX_DAYS\t90"
  tags:
    - scored
    - section5.4
    - section5.4.1
    - section5.4.1.1

- name: 5.4.1.2 Ensure minimum days between password changes is 7 or more (Scored)
  lineinfile: >
    backup=yes
    state=present
    dest=/etc/login.defs
    backrefs=yes
    regexp="^PASS_MIN_DAYS\s+"
    line="PASS_MIN_DAYS\t7"
  tags:
    - scored
    - section5.4
    - section5.4.1
    - section5.4.1.2

- name: 5.4.1.3 Ensure password expiration warning days is 7 or more (Scored)
  lineinfile: >
    backup=yes
    state=present
    dest=/etc/login.defs
    backrefs=yes
    regexp="^PASS_WARN_AGE\s+"
    line="PASS_WARN_AGE\t7"
  tags:
    - scored
    - section5.4
    - section5.4.1
    - section5.4.1.3

- name: 5.4.1.4 Ensure inactive password lock is 30 days or less (Scored)
  command: /usr/sbin/useradd -D -f 30
  when: lock_inactive
  tags:
    - scored
    - section5.4
    - section5.4.1
    - section5.4.1.4

- name: 5.4.1.4 Ensure inactive password lock is 30 days or less (Scored)
  lineinfile:
    state: present
    dest: /etc/default/useradd
    regexp: ^\s*INACTIVE\s*=\d*$
    line: "INACTIVE={{ lock_inactive_days }}"
  when:
    - lock_inactive
    - lock_inactive_days is defined
  tags:
    - scored
    - section5.4
    - section5.4.1
    - section5.4.1.4

- name: 5.4.2 Ensure system accounts are non-login (Scored) #need to verify accuracy. I think this script disables all system accounts
  shell: awk -F':' '($3<500 && $1!="root" && $1!="sync" && $1!="shutdown" && $1!="sync" && $1!="shutdown" && $1!="halt" && $7!="/sbin/nologin") { print $1 }' /etc/passwd
  register: enabled_system_accounts
  changed_when: false
  tags:
    - scored
    - section5.4
    - section5.4.2

- name: 5.4.2 Ensure system accounts are non-login (Scored)
  command: /usr/sbin/usermod -s /sbin/nologin {{ item }}
  with_items: "{{ enabled_system_accounts.stdout_lines }}"
  tags:
    - scored
    - section5.4
    - section5.4.2

- name: 5.4.3 Ensure default group for the root account is GID 0 (Scored)
  user: >
    name=root
    group=root
  tags:
    - scored
    - section5.4
    - section5.4.3

- name: 5.4.4 Ensure default user umask is 027 or more restrictive (Scored)
  lineinfile: >
    state=present
    create=yes
    dest=/etc/profile.d/cis.sh
    line="umask 027"
  ignore_errors: true
  when: set_umask
  tags:
    - scored
    - section5.4
    - section5.4.4

- name: 5.5 Ensure root login is restricted to system console (Not Scored)
  debug: msg="Too restrictive for most environments."
  tags:
    - notscored
    - section5.5

- name: 5.6 Ensure access to the su command is restricted (Scored)
  copy: >
    src=etc/pam.d/rhel-6/su
    dest=/etc/pam.d/su
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6") or
        (ansible_distribution == "RedHat" and ansible_distribution_major_version == "6")
  tags:
    - scored
    - section5.6

- name: 5.6 Ensure access to the su command is restricted (Scored)
  copy: >
    src=etc/pam.d/rhel-7/su
    dest=/etc/pam.d/su
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7") or
        (ansible_distribution == "RedHat" and ansible_distribution_major_version == "7")
  tags:
    - scored
    - section5.6
