---
#   Section 4.1 Configure System Accounting

- name: 4.1.1.1 Ensure audit log storage size is configured (Not Scored)
  lineinfile: >
    state=present
    dest=/etc/audit/auditd.conf
    regexp="^max_log_file ="
    line="max_log_file = {{ max_log_file }}"
  notify: Reload auditd Rules
  tags:
    - notscored
    - section4.1
    - section4.1.1
    - section4.1.1.1

- name: 4.1.1.2 Ensure system is disabled when audit logs are full (Scored)
  lineinfile: >
    state=present
    dest=/etc/audit/auditd.conf
    regexp="^space_left_action ="
    line="space_left_action = {{ space_left_action }}"
  notify: Reload auditd Rules
  tags:
    - scored
    - section4.1
    - section4.1.1
    - section4.1.1.2

- name: 4.1.1.2 Ensure system is disabled when audit logs are full (Scored)
  lineinfile: >
    state=present
    dest=/etc/audit/auditd.conf
    regexp="^action_mail_acct ="
    line="action_mail_acct = {{ action_mail_acct }}"
  notify: Reload auditd Rules
  tags:
    - scored
    - section4.1
    - section4.1.1
    - section4.1.1.2

- name: 4.1.1.2 Ensure system is disabled when audit logs are full (Scored)
  lineinfile: >
    state=present
    dest=/etc/audit/auditd.conf
    regexp="^admin_space_left_action ="
    line="admin_space_left_action = {{ admin_space_left_action }}"
  notify: Reload auditd Rules
  tags:
    - scored
    - section4.1
    - section4.1.1
    - section4.1.1.2

- name: 4.1.1.3 Ensure audit logs are not automatically deleted (Scored)
  lineinfile: >
    state=present
    dest=/etc/audit/auditd.conf
    regexp="^max_log_file_action ="
    line="max_log_file_action = {{ max_log_file_action }}"
  notify: Reload auditd Rules
  tags:
    - scored
    - section4.1
    - section4.1.1
    - section4.1.1.3

- name: 4.1.2 Ensure auditd service is enabled (Scored)
  service: >
    name=auditd
    enabled=yes
    state=running
  tags:
    - scored
    - section4.1
    - section4.1.2

- name: 4.1.3 Ensure auditing for processes that start prior to auditd is enabled (Scored)
  lineinfile: >
    state=present
    dest=/etc/grub.conf
    backrefs=yes
    regexp="(^\s*kernel.*)$(?<!audit=1)"
    line="\1 audit=1"
  when:
    - ansible_distribution == "RedHat"
    - ansible_distribution_major_version == "6"
  tags:
    - scored
    - section4.1
    - section4.1.3

- name: 4.1.4 - 4.1.18 Configure auditd Rules (Scored)
  copy: >
    src=etc/audit/audit.rules
    dest=/etc/audit/audit.rules
  notify: Reload auditd Rules
  tags:
    - scored
    - section4.1
    - section4.1.4
    - section4.1.5
    - section4.1.6
    - section4.1.7
    - section4.1.8
    - section4.1.9
    - section4.1.10
    - section4.1.11
    - section4.1.12
    - section4.1.13
    - section4.1.14
    - section4.1.15
    - section4.1.16
    - section4.1.17
    - section4.1.18
